# Generated by Django 4.2 on 2026-05-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sms_alert',
            field=models.CharField(choices=[('activate', 'Activate'), ('deactivate', 'Deactivate')], default='deactivate', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=20),
        ),
    ]
