# Generated by Django 4.2 on 2026-06-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_sms_alert_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_plain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
