# Generated by Django 4.2 on 2026-05-11 23:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('daily_transfer_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('single_transfer_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('allows_overdraft', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, editable=False, help_text='Auto-generated unique account number', max_length=20, unique=True, verbose_name='account number')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('NGN', 'Nigerian Naira (₦)'), ('GHS', 'Ghanaian Cedi (₵)'), ('ZAR', 'South African Rand (R)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)')], default='USD', max_length=3, verbose_name='currency')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current account balance', max_digits=15, verbose_name='balance')),
                ('transaction_pin', models.CharField(blank=True, help_text='4-6 digit PIN for authorizing transactions (hashed)', max_length=128, null=True, verbose_name='transaction PIN')),
                ('transaction_status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], default='success', max_length=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='customer.bankaccounttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebitCardApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('card_type', models.CharField(choices=[('visa', 'Visa Debit Card'), ('master', 'Master Debit Card')], max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('AED', 'AED - UAE Dirham'), ('KWD', 'KWD - Kuwaiti Dinar')], default='USD', max_length=10)),
                ('spending_limit', models.DecimalField(decimal_places=2, help_text='Daily or monthly spending limit', max_digits=12)),
                ('issuance_fee', models.CharField(choices=[('5', 'Standard - $5.00'), ('15', 'Gold - $15.00'), ('25', 'Platinum - $25.00'), ('50', 'Black - $50.00')], default='5', max_length=10)),
                ('delivery_method', models.CharField(choices=[('pickup', 'Branch Pickup'), ('home_delivery', 'Home Delivery')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_card_applications', to='customer.userbankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('visa', 'Visa Debit Card'), ('master', 'Master Debit Card')], default='visa', max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('AED', 'AED - UAE Dirham'), ('KWD', 'KWD - Kuwaiti Dinar')], default='USD', max_length=10)),
                ('card_number', models.CharField(editable=False, max_length=19, unique=True)),
                ('card_holder_name', models.CharField(max_length=150)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('spending_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('issuance_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('blocked', 'Blocked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('is_virtual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='customer.userbankaccount')),
            ],
        ),
        migrations.AddIndex(
            model_name='userbankaccount',
            index=models.Index(fields=['account_number'], name='customer_us_account_7104df_idx'),
        ),
        migrations.AddIndex(
            model_name='userbankaccount',
            index=models.Index(fields=['user', 'is_active'], name='customer_us_user_id_d789fd_idx'),
        ),
    ]
