# Generated by Django 4.2 on 2026-05-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_bankaccounttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('AED', 'UAE Dirham (د.إ)'), ('KWD', 'Kuwaiti Dinar (د.ك)'), ('JPY', 'Japanese Yen (¥)'), ('KRW', 'South Korean Won (₩)')], default='USD', max_length=3, verbose_name='currency'),
        ),
    ]
