# Generated by Django 4.2 on 2026-05-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_userbankaccount_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='account_age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
