# Generated by Django 4.2 on 2026-05-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_userbankaccount_account_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitcardapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
