# Generated by Django 4.2 on 2026-05-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_debitcardapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='payment_reference',
            field=models.CharField(blank=True, editable=False, max_length=12),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='sort_code',
            field=models.CharField(blank=True, editable=False, max_length=8),
        ),
    ]
