# Generated by Django 4.2 on 2026-05-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_userbankaccount_payment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='payment_reference',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='sort_code',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
    ]
