# Generated by Django 4.2 on 2026-05-14 10:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_userbankaccount_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounttype',
            name='activation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
