# Generated by Django 4.2 on 2026-05-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountfunding',
            name='bank_name',
            field=models.CharField(default='Dew Trust Bank', max_length=255),
        ),
        migrations.AddField(
            model_name='accountfunding',
            name='beneficiary_name',
            field=models.CharField(default='****self', max_length=255),
        ),
        migrations.AddField(
            model_name='accountfunding',
            name='beneficiary_number',
            field=models.CharField(default='******self', max_length=100),
        ),
    ]
