# Generated by Django 4.2 on 2026-05-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_accountfunding_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountfunding',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountfunding',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], default='success', max_length=20),
        ),
    ]
