# Generated by Django 4.2 on 2026-05-11 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('personal', 'Personal Loan'), ('business', 'Business Loan'), ('mortgage', 'Mortgage Loan'), ('education', 'Education Loan'), ('car', 'Car Loan')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Loan Amount', max_digits=12)),
                ('duration_months', models.PositiveIntegerField(help_text='Loan duration in months')),
                ('purpose', models.TextField(help_text='Describe the purpose of the loan')),
                ('monthly_net_income', models.CharField(choices=[('below_2000', 'Below $2,000'), ('2000_5000', '$2,000 - $5,000'), ('5000_10000', '$5,000 - $10,000'), ('above_10000', 'Above $10,000')], max_length=50)),
                ('annual_interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_repayment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('repaid', 'Repaid')], default='pending', max_length=20)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loan.loanapplication')),
            ],
        ),
    ]
