# Generated by Django 4.2 on 2026-05-19 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0002_alter_transactionhistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copied_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
