# Generated by Django 4.2 on 2026-05-11 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('title', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss'), ('dr', 'Dr'), ('prof', 'Prof')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('zipcode', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('ssn', models.CharField(max_length=100, verbose_name='State Security Number')),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('business', 'Business')], max_length=30)),
                ('employment_type', models.CharField(choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('student', 'Student'), ('unemployed', 'Unemployed')], max_length=30)),
                ('annual_income_range', models.CharField(choices=[('0-10000', '$0 - $10,000'), ('10000-50000', '$10,000 - $50,000'), ('50000-100000', '$50,000 - $100,000'), ('100000+', '$100,000+')], max_length=30)),
                ('address_line', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('beneficiary_legal_name', models.CharField(max_length=255)),
                ('next_of_kin_address', models.TextField()),
                ('relationship', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('document_type', models.CharField(choices=[('passport', 'International Passport'), ('national_id', 'National ID'), ('drivers_license', 'Drivers License')], max_length=30)),
                ('upload_front_side', models.ImageField(upload_to='kyc/front/')),
                ('upload_back_side', models.ImageField(upload_to='kyc/back/')),
                ('passport_photograph', models.ImageField(upload_to='kyc/passport/')),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kycverification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
