# Generated by Django 4.2 on 2026-05-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='account_type',
            field=models.CharField(choices=[('savings', 'Savings Account'), ('checking', 'Checking Account'), ('non_resident', 'Non-Resident Account'), ('offshore_corp', 'Offshore Corperate Account'), ('offshore_personal', '\tOffshore personal Account'), ('wealth_management', 'Wealth Management Account')], max_length=30),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='title',
            field=models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss'), ('dr', 'Dr'), ('prof', 'Prof'), ('other', 'Other')], max_length=20),
        ),
    ]
