# Generated by Django 4.2 on 2026-09-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_alter_kycverification_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycverification',
            name='passport_photograph',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/passport/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='upload_back_side',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/back/'),
        ),
        migrations.AlterField(
            model_name='kycverification',
            name='upload_front_side',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/front/'),
        ),
    ]
